service: sf-local
frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    layer: true
  localstack:
    stages: [local]

provider:
  name: aws
  runtime: python3.11
  lambdaHashingVersion: '20201221'
  region: us-west-2

functions:
  api:
    handler: wsgi_handler.handler
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    environment:
      SNOWFLAKE_ACCOUNT: 'test'
      SNOWFLAKE_USER: 'test'
      SNOWFLAKE_DATABASE: 'test'
      SNOWFLAKE_SCHEMA: 'test'
      SNOWFLAKE_WAREHOUSE: 'test'
      SNOWFLAKE_HOST: 'snowflake.localhost.localstack.cloud'
      # SNOWFLAKE_PRIVATE_KEY: ${ssm:/<ACCOUNT>.DATA_APPS_DEMO}
	  # note: the key below is a generated key for local testing, safe to check in to the repo
      SNOWFLAKE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpjjj/hPkOQ6jrVtLQyJlVCHUbUL7WgY5a59VWEzlhtK/NFdjEE8nSRcJayFkhLPgXAJSOPuQhhi+uo08cOsZwxknBt1pz548utB7ukYTT6DwoBOZTPgFxYe/LJbqfYMuwcNZrY9MJutTTvqICYtHrGGruMhy3B7+aHA+TVSdkMdR4l8xze+RY8p3QnqyAIH8ppjS93SDbUvGAvckuA7FFu98b7W6Np1tE/iRtBOd+yd24mX4uwFW20wWBxBaFvgTGwSqKiS0XX9+QiHf9G95CQXRPnO3OvVDk0q2yzZaSHDcGclm1HxBrK8yVq9wBQ4ygBSt+WJ23F53G9cA6wCjnAgMBAAECggEAHqjHeLjIOkKUyF1OSI+FXmFln5dVsr8BiUGTi3l1bkv4YAq7xBTZ8SpJDxZcO4oAoFQsCJ6prMAxXhBMrUuZd2n7i0pG0l+EPgs27qekj5bWTdw488NqCmENtbuwR8J+gnyc4RVPY1qDwngdnnXVBIBJUaIBHD2L8Wdyj48dzNmEdxcDXHVyFjPd075f3SpOEjsNzsfE6qGVvySLOAExaZ8YeG4fZx/O4Ly6/cY1JXZ2/dCrG1NJ2QWz1HXK1TA1VOw1kL7ahnmvu9yoA/2UDu7B9oJpq54Wum5bZojM0+pnERCkcly8aBbpQkIAjBCFucMJs3tfEKQMW4r/AD0ZTQKBgQDU/qKT38NCP5+Ae9hPg3LerWt112aZrUhPje7ZdplCGavu70kh2V+h2pu6t3Pj1d3io1Z5eu7HuBMj/AWPiA3beQQgWo2js621yz7x1lnUC7mufPXddgCdVBhN3M6NeQPvoPEfDRKKLlhQHkh+fT5Rizo8W2tn2unfs4pVjULffQKBgQDLykmBCwkqjDUj+LYre+9IUGU3Hx0h/v3IIv9GX6sf5+gDzLbLgV6Rn3LTa7mV31jIV/d8rsFLigqIDWTvgQ1EfM8vpacmz28EqBVCb2/7XG+UirgVLJN5+QXbZMB0yBorY71b/Stjc1rL5+CZV6A44ecEpClqWpJ/FMMZpEufMwKBgQDG/LmQoy09eEkgdRNKfcjUZnoNltZg3jW/NR+fBKD70xYA3IabXARvJtf0oa1gfo6UTPrd9U6dQciIBsx/IqGnmDCVtWO8O4IfZCmDMDmt0+J+NHpSkwrR8R3fqFlEbHmT5u09kC3w8IlLGG+r1IBjGEqo1tPKLAfxGUA02wtN1QKBgBC5HuMKBsyJCOtUw445817ZyhSF5xwdErJTvOMHgsFxhGaba/yzNxF4JjIXSvlzhJOcNGD07kPGpiqX/spwqqgOHeppC5hxuUiGiogTIPtdkIJ+B7ElIU0HFGX2lJyAtzUMUEO2ONNGahMFijbLLAi+8Pg+iG+D0zW+fGwkQVhlAoGAKMIlB9mTCPqhPni329JfY2nMFRG62oKK5ylup5IQMkPLVy9NLty00daVLkCU4DIGEnb0z9oJbzCkSokWAHxyDJRuIvuK7+iuVVhb9D753KYm/MjpB3Ysa19iqLhNf3gC8IGyyLchWLHqJkCaCHZpJS2jkjXmGNJjkTrcfgju+rU=\n-----END PRIVATE KEY-----"
    timeout: 15
    events:
      - http:
          path: /trips/monthly
          method: GET
      - http:
          path: /trips/day_of_week
          method: GET
      - http:
          path: /trips/temperature
          method: GET
      - http:
          path: /sqlapi/trips/monthly
          method: GET
      - http:
          path: /sqlapi/trips/day_of_week
          method: GET
      - http:
          path: /sqlapi/trips/temperature
          method: GET

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-localstack

package:
  patterns:
    - '!__pycache__/**'
    - '!node_modules/**'
    - '!.venv/**'
    - '!.serverless/**'
    - '!LICENSE'
    - '!README.md'
    - '!serverless-template.yml'
    - '!requirements.txt'
    - '!package.json'
    - '!package-lock.json'
